SOURCE= versioned_queue.cpp
TARGET=versioned_queue
CC=g++

#------------------------------------------------------------------------------



all: $(TARGET)

$(TARGET): $(SOURCE)

	$(CC) $(SOURCE) -o$(TARGET) -lstdc++ -std=c++11

clean:

	rm -f $(TARGET)
